# Generated by Django 2.1 on 2020-07-15 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='get_history',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name='profile',
            name='score',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='send_history',
            field=models.CharField(blank=True, max_length=8),
        ),
    ]
