# Generated by Django 2.1 on 2020-07-15 08:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccepterHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_speed', models.CharField(max_length=2, null=True)),
                ('score_service', models.CharField(max_length=2, null=True)),
                ('score_all', models.CharField(max_length=2, null=True)),
                ('times', models.CharField(default=1, max_length=6)),
                ('score_desc', models.TextField(blank=True, max_length=500)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, null=True)),
                ('startloc', models.CharField(max_length=64, null=True)),
                ('endloc', models.CharField(max_length=64, null=True)),
                ('starttime', models.DateField(blank=True, null=True)),
                ('endtime', models.DateField(blank=True, null=True)),
                ('price', models.CharField(blank=True, max_length=20)),
                ('desc', models.TextField(blank=True, max_length=300)),
                ('file', models.ImageField(upload_to='')),
                ('state', models.CharField(default='open', max_length=20)),
                ('username', models.CharField(max_length=20, null=True)),
                ('accepter', models.CharField(blank=True, max_length=20)),
                ('acceptmsg', models.CharField(blank=True, max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200, null=True)),
                ('last_name', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('username', models.CharField(max_length=200, null=True)),
                ('password', models.CharField(max_length=200, null=True)),
                ('activate', models.CharField(max_length=200, null=True)),
                ('bday', models.DateField(null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('activated', models.BooleanField(default=0)),
                ('phone', models.CharField(max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_speed', models.CharField(blank=True, max_length=2)),
                ('score_service', models.CharField(blank=True, max_length=2)),
                ('score_all', models.CharField(blank=True, max_length=2)),
                ('times', models.CharField(default=1, max_length=6)),
                ('score_desc', models.TextField(blank=True, max_length=500)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UserHistorys', to='forum.Registration')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='forum.QuestionPost'),
        ),
        migrations.AddField(
            model_name='accepterhistory',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AccepterHistorys', to='forum.Registration'),
        ),
    ]
