# Generated by Django 2.1 on 2020-06-30 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionpost',
            name='endloc',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='questionpost',
            name='endtime',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='questionpost',
            name='price',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='questionpost',
            name='startloc',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='questionpost',
            name='starttime',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='questionpost',
            name='title',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
