# Generated by Django 2.1 on 2020-07-15 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accepterhistory',
            name='times',
            field=models.CharField(default='1', max_length=6),
        ),
        migrations.AlterField(
            model_name='userhistory',
            name='score_all',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='userhistory',
            name='score_service',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='userhistory',
            name='score_speed',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='userhistory',
            name='times',
            field=models.CharField(default='1', max_length=6),
        ),
    ]
