# Generated by Django 2.1 on 2020-06-30 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_auto_20200630_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionpost',
            name='accepter',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='questionpost',
            name='owner',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
