# Generated by Django 2.1 on 2020-07-15 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_auto_20200715_1853'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accepterhistory',
            old_name='username',
            new_name='Accepter',
        ),
        migrations.RenameField(
            model_name='userhistory',
            old_name='username',
            new_name='user',
        ),
    ]
