# Generated by Django 2.1 on 2020-07-15 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_auto_20200715_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accepterhistory',
            name='Accepter',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='AccepterHistorys', to='forum.Registration'),
        ),
        migrations.AlterField(
            model_name='userhistory',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserHistorys', to='forum.Registration'),
        ),
    ]
