# Generated by Django 2.1 on 2020-06-28 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_auto_20170713_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionpost',
            name='file',
            field=models.ImageField(upload_to=''),
        ),
    ]
